dataset:
  name: mnist
model:
  name: dtikmeans
  n_prototypes: 100
  encoder_name: resnet20
  transformation_sequence: identity_affine_morpho_tps
  curriculum_learning: [50, 150, 200]
  grid_size: 4
  kernel_size: 7
training:
  knn: 4
  batch_size: 128
  optimizer:
    name: adam
    lr: 1.0e-3
    transformer:
      weight_decay: 1.0e-6
  scheduler:
    name: multi_step
    gamma: 0.1
    milestones: [280]
    update_range: epoch
  n_epochs: 300
  train_stat_interval: 25
  check_cluster_interval: 50
  seed: 42
  resume: /kolla/code/lyt/general_rknn/mnist/src/clustering/runs/mnist/clu_100